create extension if not exists pgcrypto;

create table if not exists public.crm_settings (
  id smallint primary key default 1 check (id = 1),
  telegram_bot_token text not null default '',
  telegram_bot_username text not null default '',
  telegram_chat_id text not null default '',
  telegram_enabled boolean not null default false,
  reminders_enabled boolean not null default true,
  list_action_search_enabled boolean not null default true,
  list_action_reaction_enabled boolean not null default true,
  list_action_create_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.crm_settings (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.crm_clients (
  id uuid primary key default gen_random_uuid(),
  client_number bigint generated by default as identity,
  address text not null default '',
  complex_name text not null default '',
  name text not null,
  phone text not null,
  is_proxy_phone boolean not null default false,
  commission numeric(12,2) not null default 0,
  is_duplicate boolean not null default false,
  is_exclusive boolean not null default false,
  is_archived boolean not null default false,
  link text not null default '',
  only_clients boolean not null default false,
  callback_at timestamptz,
  callback_reminded_at timestamptz,
  no_answer boolean not null default false,
  no_answer_marked_at timestamptz,
  no_answer_reminded_at timestamptz,
  notes text not null default '',
  parking_spots jsonb not null default '[]'::jsonb,
  objects jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists crm_clients_client_number_idx
  on public.crm_clients (client_number);

create index if not exists crm_clients_callback_at_idx
  on public.crm_clients (callback_at)
  where callback_at is not null;

create index if not exists crm_clients_no_answer_idx
  on public.crm_clients (no_answer_marked_at)
  where no_answer = true and no_answer_marked_at is not null and no_answer_reminded_at is null;

create index if not exists crm_clients_is_archived_idx
  on public.crm_clients (is_archived)
  where is_archived = true;

create table if not exists public.crm_notification_log (
  id bigserial primary key,
  client_id uuid not null references public.crm_clients(id) on delete cascade,
  kind text not null,
  payload jsonb not null default '{}'::jsonb,
  sent_at timestamptz not null default now()
);

create unique index if not exists crm_notification_log_unique_idx
  on public.crm_notification_log (client_id, kind);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_crm_settings_updated_at on public.crm_settings;
create trigger trg_crm_settings_updated_at
before update on public.crm_settings
for each row execute function public.set_updated_at();

drop trigger if exists trg_crm_clients_updated_at on public.crm_clients;
create trigger trg_crm_clients_updated_at
before update on public.crm_clients
for each row execute function public.set_updated_at();
