create schema if not exists crm;

create or replace function crm.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists crm.owners (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text,
  phone_type text not null default 'неизвестно',
  telegram text,
  email text,
  role text not null default 'Собственник',
  source text not null default 'Входящий',
  preferred_channel text not null default 'Telegram',
  object_type text,
  rooms text,
  address text,
  price_expectation_rub integer not null default 0,
  work_mode text not null default 'Эксклюзив',
  access_mode_json text not null default '[]',
  documents_json text not null default '[]',
  stage_key text not null default 'no-answer',
  next_action text,
  next_action_at text,
  agent_experience text,
  leads_state text,
  showings_state text,
  commission_pct numeric(5,2),
  cooperation_state text,
  duplicate_state text,
  exclusive_state text,
  deal_type text,
  object_complex text,
  object_price_text text,
  object_link text,
  return_at text,
  last_contact_at text,
  touch_count integer not null default 0,
  responsible text,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists crm.clients (
  id bigint generated by default as identity primary key,
  full_name text not null,
  telegram text,
  email text,
  source text not null default 'Входящий',
  preferred_channel text not null default 'Telegram',
  request_type text not null default 'Долгосрочная аренда',
  property_type text not null default 'Квартира',
  rooms text,
  budget_from_rub integer not null default 0,
  budget_to_rub integer not null default 0,
  preferred_areas text,
  preferred_metro text,
  move_in_window text,
  rent_term text,
  preferences_json text not null default '[]',
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists crm.residential_rent_objects (
  id bigint generated by default as identity primary key,
  owner_id bigint references crm.owners(id) on delete set null,
  deal_type text not null default 'long_rent',
  category text not null default 'residential',
  object_type text not null,
  room_mode text,
  total_area_m2 numeric(10,2),
  living_area_m2 numeric(10,2),
  kitchen_area_m2 numeric(10,2),
  layout_type text,
  ceiling_height_m numeric(10,2),
  floor_number integer,
  floors_total integer,
  address text not null,
  apartment_number text,
  cadastral_number text,
  realty_kind text not null default 'Квартира',
  photo_count integer not null default 0,
  photo_files_json text not null default '[]',
  balcony_count integer not null default 0,
  loggia_count integer not null default 0,
  window_views_json text not null default '[]',
  bathroom_separate_count integer not null default 0,
  bathroom_combined_count integer not null default 0,
  renovation_type text,
  elevator_passenger_count integer not null default 0,
  elevator_cargo_count integer not null default 0,
  entrance_features_json text not null default '[]',
  parking_types_json text not null default '[]',
  furniture_json text not null default '[]',
  bathroom_features_json text not null default '[]',
  appliances_json text not null default '[]',
  connectivity_json text not null default '[]',
  description text,
  title text,
  rent_price_rub integer not null default 0,
  utilities_payer text,
  prepayment_months text,
  deposit_rub integer not null default 0,
  rent_term text,
  living_conditions_json text not null default '[]',
  other_agent_commission_pct numeric(5,2),
  renter_commission_pct numeric(5,2),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists crm.client_requests (
  id bigint generated by default as identity primary key,
  client_id bigint not null references crm.clients(id) on delete cascade,
  funnel_key text not null default 'selection',
  stage_key text not null default 'clarify',
  property_type text,
  rooms text,
  budget_from_rub integer not null default 0,
  budget_to_rub integer not null default 0,
  preferred_areas text,
  preferred_metro text,
  move_in_window text,
  rent_term text,
  preferences_json text not null default '[]',
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists crm.funnel_cards (
  id bigint generated by default as identity primary key,
  funnel_key text not null,
  stage_key text not null,
  owner_id bigint references crm.owners(id) on delete set null,
  client_id bigint references crm.clients(id) on delete set null,
  object_id bigint references crm.residential_rent_objects(id) on delete set null,
  request_id bigint references crm.client_requests(id) on delete set null,
  title text not null,
  amount_text text,
  status_text text,
  person_name text,
  badge_text text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_crm_residential_rent_objects_owner_id
  on crm.residential_rent_objects (owner_id);

alter table if exists crm.residential_rent_objects
  add column if not exists photo_files_json text not null default '[]';

alter table if exists crm.residential_rent_objects
  add column if not exists rent_type text;

alter table if exists crm.residential_rent_objects
  add column if not exists status text;

alter table if exists crm.residential_rent_objects
  add column if not exists property_type text;

alter table if exists crm.residential_rent_objects
  add column if not exists internal_title text;

alter table if exists crm.residential_rent_objects
  add column if not exists residential_complex_name text;

alter table if exists crm.residential_rent_objects
  add column if not exists short_description text;

alter table if exists crm.residential_rent_objects
  add column if not exists full_description text;

alter table if exists crm.residential_rent_objects
  add column if not exists city text;

alter table if exists crm.residential_rent_objects
  add column if not exists street text;

alter table if exists crm.residential_rent_objects
  add column if not exists house_number text;

alter table if exists crm.residential_rent_objects
  add column if not exists building_number text;

alter table if exists crm.residential_rent_objects
  add column if not exists block_number text;

alter table if exists crm.residential_rent_objects
  add column if not exists entrance_number text;

alter table if exists crm.residential_rent_objects
  add column if not exists underground_station text;

alter table if exists crm.residential_rent_objects
  add column if not exists underground_time_minutes integer;

alter table if exists crm.residential_rent_objects
  add column if not exists underground_transport_type text;

alter table if exists crm.residential_rent_objects
  add column if not exists lat numeric(12,8);

alter table if exists crm.residential_rent_objects
  add column if not exists lng numeric(12,8);

alter table if exists crm.residential_rent_objects
  add column if not exists currency text;

alter table if exists crm.residential_rent_objects
  add column if not exists deposit_amount numeric(12,2);

alter table if exists crm.residential_rent_objects
  add column if not exists commission_amount numeric(12,2);

alter table if exists crm.residential_rent_objects
  add column if not exists commission_type text;

alter table if exists crm.residential_rent_objects
  add column if not exists utilities_mode text;

alter table if exists crm.residential_rent_objects
  add column if not exists utilities_comment text;

alter table if exists crm.residential_rent_objects
  add column if not exists minimum_rent_term_months integer;

alter table if exists crm.residential_rent_objects
  add column if not exists is_studio boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists is_free_layout boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists windows_view text;

alter table if exists crm.residential_rent_objects
  add column if not exists repair_type text;

alter table if exists crm.residential_rent_objects
  add column if not exists furniture_mode text;

alter table if exists crm.residential_rent_objects
  add column if not exists has_bath boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists has_shower boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists has_conditioner boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists has_refrigerator boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists has_dishwasher boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists has_tv boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists has_washer boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists has_internet boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists has_phone boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists has_wardrobe_room boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists has_storage_room boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists has_panoramic_windows boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists has_terrace boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists has_fireplace boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists passenger_lifts_count integer;

alter table if exists crm.residential_rent_objects
  add column if not exists cargo_lifts_count integer;

alter table if exists crm.residential_rent_objects
  add column if not exists has_ramp boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists has_garbage_chute boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists has_concierge boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists has_security boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists video_url text;

alter table if exists crm.residential_rent_objects
  add column if not exists vk_video_url text;

alter table if exists crm.residential_rent_objects
  add column if not exists tour_3d_url text;

alter table if exists crm.residential_rent_objects
  add column if not exists layout_image_url text;

alter table if exists crm.residential_rent_objects
  add column if not exists external_id text;

alter table if exists crm.residential_rent_objects
  add column if not exists xml_category text;

alter table if exists crm.residential_rent_objects
  add column if not exists is_ready_for_export boolean;

alter table if exists crm.residential_rent_objects
  add column if not exists manager_id text;

alter table if exists crm.residential_rent_objects
  add column if not exists liquidity_level text;

alter table if exists crm.residential_rent_objects
  add column if not exists market_price_level text;

alter table if exists crm.residential_rent_objects
  add column if not exists agent_comment text;

alter table if exists crm.residential_rent_objects
  add column if not exists basic_info_json text;

alter table if exists crm.residential_rent_objects
  add column if not exists location_json text;

alter table if exists crm.residential_rent_objects
  add column if not exists pricing_json text;

alter table if exists crm.residential_rent_objects
  add column if not exists layout_json text;

alter table if exists crm.residential_rent_objects
  add column if not exists interior_json text;

alter table if exists crm.residential_rent_objects
  add column if not exists building_json text;

alter table if exists crm.residential_rent_objects
  add column if not exists media_json text;

alter table if exists crm.residential_rent_objects
  add column if not exists publication_json text;

alter table if exists crm.residential_rent_objects
  add column if not exists crm_meta_json text;

alter table if exists crm.owners
  add column if not exists phone text;

alter table if exists crm.owners
  add column if not exists phone_type text not null default 'неизвестно';

alter table if exists crm.owners
  add column if not exists stage_key text not null default 'no-answer';

alter table if exists crm.owners
  add column if not exists next_action text;

alter table if exists crm.owners
  add column if not exists next_action_at text;

alter table if exists crm.owners
  add column if not exists agent_experience text;

alter table if exists crm.owners
  add column if not exists leads_state text;

alter table if exists crm.owners
  add column if not exists showings_state text;

alter table if exists crm.owners
  add column if not exists commission_pct numeric(5,2);

alter table if exists crm.owners
  add column if not exists cooperation_state text;

alter table if exists crm.owners
  add column if not exists duplicate_state text;

alter table if exists crm.owners
  add column if not exists exclusive_state text;

alter table if exists crm.owners
  add column if not exists deal_type text;

alter table if exists crm.owners
  add column if not exists object_complex text;

alter table if exists crm.owners
  add column if not exists object_price_text text;

alter table if exists crm.owners
  add column if not exists object_link text;

alter table if exists crm.owners
  add column if not exists return_at text;

alter table if exists crm.owners
  add column if not exists last_contact_at text;

alter table if exists crm.owners
  add column if not exists touch_count integer not null default 0;

alter table if exists crm.owners
  add column if not exists responsible text;

create index if not exists idx_crm_client_requests_client_id
  on crm.client_requests (client_id);

create index if not exists idx_crm_funnel_cards_funnel_stage
  on crm.funnel_cards (funnel_key, stage_key, created_at desc);

drop trigger if exists set_updated_at_on_owners on crm.owners;
create trigger set_updated_at_on_owners
before update on crm.owners
for each row
execute function crm.set_updated_at();

drop trigger if exists set_updated_at_on_clients on crm.clients;
create trigger set_updated_at_on_clients
before update on crm.clients
for each row
execute function crm.set_updated_at();

drop trigger if exists set_updated_at_on_residential_rent_objects on crm.residential_rent_objects;
create trigger set_updated_at_on_residential_rent_objects
before update on crm.residential_rent_objects
for each row
execute function crm.set_updated_at();

drop trigger if exists set_updated_at_on_client_requests on crm.client_requests;
create trigger set_updated_at_on_client_requests
before update on crm.client_requests
for each row
execute function crm.set_updated_at();

drop trigger if exists set_updated_at_on_funnel_cards on crm.funnel_cards;
create trigger set_updated_at_on_funnel_cards
before update on crm.funnel_cards
for each row
execute function crm.set_updated_at();
