PRAGMA foreign_keys = ON;

CREATE TABLE owners (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  full_name TEXT NOT NULL,
  telegram TEXT,
  email TEXT,
  role TEXT NOT NULL DEFAULT 'Собственник',
  source TEXT NOT NULL DEFAULT 'Входящий',
  preferred_channel TEXT NOT NULL DEFAULT 'Telegram',
  object_type TEXT,
  rooms TEXT,
  address TEXT,
  price_expectation_rub INTEGER NOT NULL DEFAULT 0,
  work_mode TEXT NOT NULL DEFAULT 'Эксклюзив',
  access_mode_json TEXT NOT NULL DEFAULT '[]',
  documents_json TEXT NOT NULL DEFAULT '[]',
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE clients (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  full_name TEXT NOT NULL,
  telegram TEXT,
  email TEXT,
  source TEXT NOT NULL DEFAULT 'Входящий',
  preferred_channel TEXT NOT NULL DEFAULT 'Telegram',
  request_type TEXT NOT NULL DEFAULT 'Долгосрочная аренда',
  property_type TEXT NOT NULL DEFAULT 'Квартира',
  rooms TEXT,
  budget_from_rub INTEGER NOT NULL DEFAULT 0,
  budget_to_rub INTEGER NOT NULL DEFAULT 0,
  preferred_areas TEXT,
  preferred_metro TEXT,
  move_in_window TEXT,
  rent_term TEXT,
  preferences_json TEXT NOT NULL DEFAULT '[]',
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE residential_rent_objects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_id INTEGER REFERENCES owners(id) ON DELETE SET NULL,
  deal_type TEXT NOT NULL DEFAULT 'long_rent',
  category TEXT NOT NULL DEFAULT 'residential',
  object_type TEXT NOT NULL,
  room_mode TEXT,
  total_area_m2 REAL,
  living_area_m2 REAL,
  kitchen_area_m2 REAL,
  layout_type TEXT,
  ceiling_height_m REAL,
  floor_number INTEGER,
  floors_total INTEGER,
  address TEXT NOT NULL,
  apartment_number TEXT,
  cadastral_number TEXT,
  realty_kind TEXT NOT NULL DEFAULT 'Квартира',
  photo_count INTEGER NOT NULL DEFAULT 0,
  balcony_count INTEGER NOT NULL DEFAULT 0,
  loggia_count INTEGER NOT NULL DEFAULT 0,
  window_views_json TEXT NOT NULL DEFAULT '[]',
  bathroom_separate_count INTEGER NOT NULL DEFAULT 0,
  bathroom_combined_count INTEGER NOT NULL DEFAULT 0,
  renovation_type TEXT,
  elevator_passenger_count INTEGER NOT NULL DEFAULT 0,
  elevator_cargo_count INTEGER NOT NULL DEFAULT 0,
  entrance_features_json TEXT NOT NULL DEFAULT '[]',
  parking_types_json TEXT NOT NULL DEFAULT '[]',
  furniture_json TEXT NOT NULL DEFAULT '[]',
  bathroom_features_json TEXT NOT NULL DEFAULT '[]',
  appliances_json TEXT NOT NULL DEFAULT '[]',
  connectivity_json TEXT NOT NULL DEFAULT '[]',
  description TEXT,
  title TEXT,
  rent_price_rub INTEGER NOT NULL DEFAULT 0,
  utilities_payer TEXT,
  prepayment_months TEXT,
  deposit_rub INTEGER NOT NULL DEFAULT 0,
  rent_term TEXT,
  living_conditions_json TEXT NOT NULL DEFAULT '[]',
  other_agent_commission_pct REAL,
  renter_commission_pct REAL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE client_requests (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  client_id INTEGER NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  funnel_key TEXT NOT NULL DEFAULT 'selection',
  stage_key TEXT NOT NULL DEFAULT 'clarify',
  property_type TEXT,
  rooms TEXT,
  budget_from_rub INTEGER NOT NULL DEFAULT 0,
  budget_to_rub INTEGER NOT NULL DEFAULT 0,
  preferred_areas TEXT,
  preferred_metro TEXT,
  move_in_window TEXT,
  rent_term TEXT,
  preferences_json TEXT NOT NULL DEFAULT '[]',
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE funnel_cards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  funnel_key TEXT NOT NULL,
  stage_key TEXT NOT NULL,
  owner_id INTEGER REFERENCES owners(id) ON DELETE SET NULL,
  client_id INTEGER REFERENCES clients(id) ON DELETE SET NULL,
  object_id INTEGER REFERENCES residential_rent_objects(id) ON DELETE SET NULL,
  request_id INTEGER REFERENCES client_requests(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  amount_text TEXT,
  status_text TEXT,
  person_name TEXT,
  badge_text TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
