CREATE TABLE residential_rent_objects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  deal_type TEXT NOT NULL DEFAULT 'long_rent',
  category TEXT NOT NULL DEFAULT 'residential',
  object_type TEXT NOT NULL,
  room_mode TEXT,
  total_area_m2 REAL,
  living_area_m2 REAL,
  kitchen_area_m2 REAL,
  layout_type TEXT,
  ceiling_height_m REAL,
  floor_number INTEGER,
  floors_total INTEGER,
  address TEXT NOT NULL,
  apartment_number TEXT,
  cadastral_number TEXT,
  realty_kind TEXT NOT NULL DEFAULT 'Квартира',
  photo_count INTEGER NOT NULL DEFAULT 0,
  balcony_count INTEGER NOT NULL DEFAULT 0,
  loggia_count INTEGER NOT NULL DEFAULT 0,
  window_views_json TEXT NOT NULL DEFAULT '[]',
  bathroom_separate_count INTEGER NOT NULL DEFAULT 0,
  bathroom_combined_count INTEGER NOT NULL DEFAULT 0,
  renovation_type TEXT,
  elevator_passenger_count INTEGER NOT NULL DEFAULT 0,
  elevator_cargo_count INTEGER NOT NULL DEFAULT 0,
  entrance_features_json TEXT NOT NULL DEFAULT '[]',
  parking_types_json TEXT NOT NULL DEFAULT '[]',
  furniture_json TEXT NOT NULL DEFAULT '[]',
  bathroom_features_json TEXT NOT NULL DEFAULT '[]',
  appliances_json TEXT NOT NULL DEFAULT '[]',
  connectivity_json TEXT NOT NULL DEFAULT '[]',
  description TEXT,
  title TEXT,
  rent_price_rub INTEGER NOT NULL DEFAULT 0,
  utilities_payer TEXT,
  prepayment_months TEXT,
  deposit_rub INTEGER NOT NULL DEFAULT 0,
  rent_term TEXT,
  living_conditions_json TEXT NOT NULL DEFAULT '[]',
  other_agent_commission_pct REAL,
  renter_commission_pct REAL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
