alter table public.crm_clients
  add column if not exists client_number bigint generated by default as identity;

update public.crm_clients
set client_number = default
where client_number is null;

alter table public.crm_clients
  alter column client_number set not null;

create unique index if not exists crm_clients_client_number_idx
  on public.crm_clients (client_number);
